### model
model_name_or_path: pretrain_ckp/esmfold_v1

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
esmfold: true

### dataset
dataset_dir:
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 32
G_len: 16
max_length: 1024

### output
output_dir: saves/esm
logging_steps: 100
save_steps: 500
plot_loss: true
# overwrite_output_dir: true
save_safetensors: False

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
# warmup_ratio: 0.1
warmup_steps: 2000
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500

report_to: tensorboard
